<template lang="pug">
  .curso-main-container.pb-3
    BannerInterno(icono="far fa-question-circle" titulo="Actividad didáctica")
    .container.tarjeta.tarjeta--blanca.p-4.p-md-5
  
      #Actividad                
        <Actividad :cuestionario="cuestionario"/>
  
  </template>

<script>
export default {
  name: 'ActividadDidactica',
  data: () => ({
    cuestionario: {
      tema: 'tema_actividad_didactica',
      titulo: 'Cuestionario',
      introduccion: 'texto_introductorio_actividad_didactica',
      barajarPreguntas: true,
      preguntas: [
        {
          id: 1,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen1.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 2,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen2.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 3,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen3.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 4,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen4.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 5,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen5.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 6,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen1.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 7,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen2.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 8,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen3.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 9,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen4.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 10,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen5.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 11,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen1.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 12,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen2.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 13,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen3.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 14,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen4.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 15,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen5.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 16,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen1.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 17,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen2.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 18,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen3.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 19,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen4.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
        {
          id: 20,
          texto: 'texto_pregunta',
          imagen: require('@/assets/actividad/imagen5.png'),
          barajarRespuestas: true,
          opciones: [
            { id: 'a', texto: 'opcion_1', esCorrecta: false },
            { id: 'b', texto: 'opcion_2', esCorrecta: false },
            { id: 'c', texto: 'opcion_3', esCorrecta: false },
            { id: 'c', texto: 'opcion_4', esCorrecta: false },
          ],
          mensaje_correcto: '¡Muy bien! Ha acertado la respuesta.',
          mensaje_incorrecto: 'Lo sentimos, su respuesta no es la correcta.',
        },
      ],
      mensaje_final_aprobado:
        '¡Excelente! Lo felicito, ha superado la actividad y demuestra sólidos conocimientos sobre el componente formativo.',
      mensaje_final_reprobado:
        'No ha superado la actividad. Le recomendamos volver a revisar el componente formativo e intentar nuevamente la actividad didáctica.',
    },
  }),
}
</script>
