name: Crear Dist y Publicar a GitHub Pages

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.19.0

      - name: Instalar dependencias
        run: npm install

      - name: Construir dist
        run: npm run build

      - name: Publicar en gh-pages
        run: |
          git config user.name dfvelasco
          git config user.email dfvelasco@sena.edu.co
          git checkout -b newdist
          git add --force dist
          git commit -m "new dist"
          git push -u origin newdist
          git subtree push --prefix dist origin gh-pages
          git push origin --delete newdist